### ISSUE TITLE
Error After Launching the app and try to do navigation in the Launched App

### ISSUE THREAD

**Issue by rdhandapani88** [rokuality/rokuality-java#18]
Getting the below error message while launching the app , and try to navigate in the app.

com.rokuality.core.exceptions.SessionNotStartedException: Failed to start image collection on the device! Is the device provisionsed properly for test and listening at 192.168.6.109
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.rokuality.core.driver.ServerPostHandler.postToServerWithHandling(ServerPostHandler.java:25)
	at com.rokuality.core.driver.roku.RokuDriver.<init>(RokuDriver.java:38)
	at com.rokuality.test.tests.RokuTests.rokuRemoteControl(RokuTests.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

**Comment by baclark774** [comment]
Looks like the image collection was not able to start on the device. You should have a ~/Rokuality/logs directory on the machine running the server. Can you provide the contents of that directory? If you don't wish to post it here you can email us at rokualitydevs@rokuality.com and include it. Also can you share what your test session capabilities look like on test start for this test?

**Comment by rdhandapani88** [comment]
DeviceCapabilities capabilities = new DeviceCapabilities();

		// Indicates we want a Roku test session
		capabilities.addCapability("Platform", "Roku");

		// OCR module - Options are 'Tesseract' or 'GoogleVision'
		capabilities.addCapability("OCRType", "Tesseract");
                capabilities.addCapability("App", "53725");
		
		// Your Roku device ip address.
		capabilities.addCapability("DeviceIPAddress", "192.168.1.89");

		// Your Roku device username and password as created during your device
		// developer setup.
		capabilities.addCapability("DeviceUsername", "rokudev");
		capabilities.addCapability("DevicePassword", "test1234");
		
		// OPTIONAL A base image match similarity tolerance between 0 and 1
		capabilities.addCapability("ImageMatchSimilarity", .89);

		capabilities.addCapability("ScreenSizeOverride", "1280x820");

		return capabilities;

**Comment by baclark774** [comment]
Thanks. So looks like you're trying to test a live channel instead of a sideloaded zip. If you use the 'App' capability and don't use the 'AppPackage' capability then you must have a connected hdmi usb capture card for the roku and machine running the rokuality server.

Unfortunately there's an underlying limitation of the Roku development api's being used where they don't allow evaluations against any apps but a sideloaded development .zip.

We work around this by providing support with hdmi usb capture cards allowing us to get past this limitation and still allow testing to work with both the By.Text and By.Image based locator types using OCR and Image evaluation technologies under the hood. But the native based RokuBy locators will not work in this case as Roku WebDriver will only work with a dev channel.

So if you wish to test a production application on the device you'll need a supported usb to hdmi capture card and then provide the 'VideoCaptureInput' and 'AudioCaptureInput' capabilities as mentioned in the Device Capabilities section of the ReadME.

The Roku setup instructions have a section including links to our tested capture cards:

https://github.com/rokuality/rokuality-server#getting-started-roku

**Comment by rdhandapani88** [comment]
Cool. Thanks for the Quick Response. Will try to do that and keep you posted, Closing the issue as of now, as this is working fine in side loaded dev version of app.
