### ISSUE TITLE
Roku sendkey are not working

### ISSUE THREAD

**Issue by rdhandapani88** [rokuality/rokuality-java#20]
rokuDriver.remote().sendKeys("typing out hello world on a search screen"), are not working.

Remote driver version - Initial driver version.

**Comment by rdhandapani88** [comment]
Server used -  rokuality-server-1.2.1.jar

**Comment by baclark774** [comment]
Hello @rdhandapani88 - are you on a roku search screen with the roku soft keyboard visible? Sending literal characters will only work in that scenario.

Also that server version is somewhat old. Can you try updating to latest 1.2.5:
https://github.com/rokuality/rokuality-server/releases

The newer releases are strongly recommended as they contain the necessary support for the newer backend roku webdriver in addition to many bug fixes and performance optimizations.

**Comment by rdhandapani88** [comment]
Thanks,

I have upgraded to the latest releases, but i am getting the following error,

com.rokuality.core.exceptions.SessionNotStartedException: Roku WebDriver was not running and could not be started. Please see the README to ensure all dependencies are properly installed.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)


I have started the Server - 
java -Dport=youport -jar rokuality-server-1.2.5.jar

**Comment by rdhandapani88** [comment]
Entire log is shown below,

[RemoteTestNG] detected TestNG version 6.9.10
[TestNG] Running:
  /private/var/folders/8q/wwqxnry133zbw7tn_6k495500000gp/T/testng-eclipse--470904434/testng-customsuite.xml

java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1593)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at com.rokuality.core.httpexecutor.HttpClient.postToServer(HttpClient.java:53)
	at com.rokuality.core.driver.ServerPostHandler.postToServerWithHandling(ServerPostHandler.java:20)
	at com.rokuality.core.driver.roku.RokuDriver.<init>(RokuDriver.java:37)
	at com.rokuality.test.tests.RokuTests.remoteTest(RokuTests.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
FAILED: remoteTest
com.rokuality.core.exceptions.ServerFailureException: The server failed to respond at http://localhost:7777. Is the server listening at this location?
	at com.rokuality.core.httpexecutor.HttpClient.postToServer(HttpClient.java:98)
	at com.rokuality.core.driver.ServerPostHandler.postToServerWithHandling(ServerPostHandler.java:20)
	at com.rokuality.core.driver.roku.RokuDriver.<init>(RokuDriver.java:37)
	at com.rokuality.test.tests.RokuTests.remoteTest(RokuTests.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)


===============================================
    Default test
    Tests run: 1, Failures: 1, Skips: 0
===============================================


===============================================
Default suite
Total tests run: 1, Failures: 1, Skips: 0
===============================================

[TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@709ba3fb: 17 ms
[TestNG] Time taken by org.testng.reporters.jq.Main@525b461a: 29 ms
[TestNG] Time taken by org.testng.reporters.EmailableReporter2@64d2d351: 6 ms
[TestNG] Time taken by [FailedReporter passed=0 failed=0 skipped=0]: 3 ms
[TestNG] Time taken by org.testng.reporters.XMLReporter@35fc6dc4: 4 ms
[TestNG] Time taken by org.testng.reporters.JUnitReportReporter@491666ad: 2 ms

**Comment by rdhandapani88** [comment]
Its My bad, I have given the Roku dev credentials incorrect. Closing the bug as of now.
