### ISSUE TITLE
Roku WebDriver was not running and could not be started

### ISSUE THREAD

**Issue by rdhandapani88** [rokuality/rokuality-java#21]
After starting the latest Roku driver, and Latest Java code, getting the below errors,

Error Log:

[RemoteTestNG] detected TestNG version 6.9.10
[TestNG] Running:
  /private/var/folders/8q/wwqxnry133zbw7tn_6k495500000gp/T/testng-eclipse-1572551170/testng-customsuite.xml

FAILED: remoteTest
com.rokuality.core.exceptions.SessionNotStartedException: Roku WebDriver was not running and could not be started. Please see the README to ensure all dependencies are properly installed.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.rokuality.core.driver.ServerPostHandler.postToServerWithHandling(ServerPostHandler.java:25)
	at com.rokuality.core.driver.roku.RokuDriver.<init>(RokuDriver.java:37)
	at com.rokuality.test.tests.RokuTests.remoteTest(RokuTests.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

===============================================
    Default test
    Tests run: 1, Failures: 1, Skips: 0
===============================================

===============================================
Default suite
Total tests run: 1, Failures: 1, Skips: 0
===============================================

[TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@709ba3fb: 15 ms
[TestNG] Time taken by org.testng.reporters.jq.Main@525b461a: 22 ms
[TestNG] Time taken by org.testng.reporters.EmailableReporter2@64d2d351: 9 ms
[TestNG] Time taken by [FailedReporter passed=0 failed=0 skipped=0]: 4 ms
[TestNG] Time taken by org.testng.reporters.XMLReporter@35fc6dc4: 4 ms
[TestNG] Time taken by org.testng.reporters.JUnitReportReporter@491666ad: 3 ms

**Comment by baclark774** [comment]
Looks like an issue with the environment setup for Roku webdriver. Inside your ~/Rokuality/logs directory there should be a roku webdriver log. Can you share the contents of that? Also in your ~/Rokuaity/temp directory there should be a StartRokuWebdriver shell/batch script - what happens when you try to manually run that?

**Comment by rdhandapani88** [comment]
i dont see any "StartRokuWebdriver shell/batch script " in the temp folder. it is empty.

**Comment by baclark774** [comment]
Can you check in ~/Rokuality/logs for the most recent log file containing:

startrokuwebdriver.log

And share the content.

**Comment by rdhandapani88** [comment]
nohup: /Users/a206639227/Rokuality/dependencies/automated-channel-testing-122219/src/main: Permission denied

**Comment by baclark774** [comment]
Hmmm interesting. We should give permission to that automatically. I'll double check the server code to see if there's something up. In the interim go ahead and give full permissions to that entire directory:

chmod -R 777 /Users/****/Rokuality/dependencies/automated-channel-testing-122219

**Comment by baclark774** [comment]
I also just cut a debug build for the 1.2.6 release which may help you:
https://rokualitypublic.s3.amazonaws.com/rokuality-server-1.2.6-DEBUG.jar
You'll just have to delete that directory above and then let it re-install everything and set permissions to it properly on install when the server restarts.

**Comment by rdhandapani88** [comment]
cool, i will give a try and let you know. Thanks

**Comment by rdhandapani88** [comment]
It is working fine now, I am not seeing web-driver exceptions. Hence closing the issue.
