### ISSUE TITLE
Getting error while launching XBox , using Harmony

### ISSUE THREAD

**Issue by rdhandapani88** [rokuality/rokuality-java#23]
I have setup all the required as per the document, Procured LG harmony hub , and added devices as well, But when we run the test, we are getting the below issue.

FAILED: installFromUrlTest
com.rokuality.core.exceptions.SessionNotStartedException: The logitech harmony device at 192.168.1.146 did not respond, or your DeviceName capability does not match the device name as saved in your harmony. Is the device online and reachable on your network? See the README for details on configuring your harmony hub for test
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.rokuality.core.driver.ServerPostHandler.postToServerWithHandling(ServerPostHandler.java:25)
	at com.rokuality.core.driver.xbox.XBoxDriver.<init>(XBoxDriver.java:37)
	at com.rokuality.test.tests.XBoxTests.installFromUrlTest(XBoxTests.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

**Comment by baclark774** [comment]
Inside your logs directory in the event log you should see logging indicating something like:
Sending %s command to harmony... with the exact command being sent to the executor. What do you get when you run that command directly from the terminal?

**Comment by baclark774** [comment]
And in related new we have a build coming sometime this week that entirely removes the dependency on the harmony hubs for XBox. I'm hoping to have it out tomorrow or tuesday and will update when it's available.

**Comment by baclark774** [comment]
Rokuality server [1.2.7](https://github.com/rokuality/rokuality-server/releases) release is now available which removes the harmony hub dependency for xbox in favor of the openxbox smartglass rest api.

Please checkout out the server readme xbox dependency section as the dependencies for xbox automation have changed a bit. Notably:

You must have python 3.5 > < 3.8 installed. Python version 3.8.1 has not been succesfully tested yet.
You must have the openxbox xbox-smartglass-rest server installed and on your path. Easily done via pip3 install xbox-smartglass-rest

**Comment by rdhandapani88** [comment]
Sure, Validating that right now. Will let you know.

**Comment by baclark774** [comment]
Also please be sure to checkout the java readme for the updates XBox capabilities as they have changed slightly. You now need to provide the xbox live username/password/console id on session startup so it can connect to the console.

**Comment by rdhandapani88** [comment]
Validated the server 1.2.7 , i can launch the app with out harmony hub , in to Xbox. But we are getting below error, after the app is launched.

FAILED: launchAlreadyInstalledApp
com.rokuality.core.exceptions.SessionNotStartedException: Failed to connect device XBOXONE with the XBox Smartglass api server with result code 403.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.rokuality.core.driver.ServerPostHandler.postToServerWithHandling(ServerPostHandler.java:25)
	at com.rokuality.core.driver.xbox.XBoxDriver.<init>(XBoxDriver.java:37)
	at com.rokuality.test.tests.XBoxTests.launchAlreadyInstalledApp(XBoxTests.java:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)


===============================================
    Default test
    Tests run: 1, Failures: 1, Skips: 0
===============================================


===============================================
Default suite
Total tests run: 1, Failures: 1, Skips: 0
===============================================

[TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@709ba3fb: 16 ms
[TestNG] Time taken by org.testng.reporters.jq.Main@525b461a: 23 ms
[TestNG] Time taken by org.testng.reporters.EmailableReporter2@64d2d351: 5 ms
[TestNG] Time taken by [FailedReporter passed=0 failed=0 skipped=0]: 3 ms
[TestNG] Time taken by org.testng.reporters.XMLReporter@35fc6dc4: 4 ms
[TestNG] Time taken by org.testng.reporters.JUnitReportReporter@491666ad: 2 ms


Installations done :
pip3 install xbox-smartglass-rest

Python3 version:
Python 3.7.6

while installing xbox-smartglass-rest, all downloaded correctly, but getting one error at last, like below,

ERROR: xbox-smartglass-core 1.0.12 has requirement urwid==2.0.1, but you'll have urwid 2.1.0 which is incompatible.
Installing collected packages: marshmallow, marshmallow-objects, greenlet, gevent, appdirs, urwid, demjson, xbox-webapi, construct, asn1crypto, pycparser, cffi, cryptography, dpkt, xbox-smartglass-core, xbox-smartglass-stump, MarkupSafe, Jinja2, Werkzeug, itsdangerous, click, Flask, xbox-smartglass-rest
Successfully installed Flask-1.1.1 Jinja2-2.11.1 MarkupSafe-1.1.1 Werkzeug-1.0.0 appdirs-1.4.3 asn1crypto-1.3.0 cffi-1.14.0 click-7.0 construct-2.9.41 cryptography-2.3.1 demjson-2.2.4 dpkt-1.9.1 gevent-1.3.7 greenlet-0.4.15 itsdangerous-1.1.0 marshmallow-3.4.0 marshmallow-objects-2.1.0 pycparser-2.19 urwid-2.1.0 xbox-smartglass-core-1.0.12 xbox-smartglass-rest-0.9.8 xbox-smartglass-stump-0.9.5 xbox-webapi-1.1.7

**Comment by baclark774** [comment]
Don't think that "XBOXONE" cap value is correct. It should be the xbox console id of your console.

// XBox Live username and password
    capabilities.addCapability("DeviceUsername", "console_xbox_live_username");
    capabilities.addCapability("DevicePassword", "console_xbox_live_password");

    // The XBox live  console id
    // can be found from your xbox dev settings page at https://your_xbox_device_ip:11443/#Settings
	capabilities.addCapability("DeviceID", "xbox_live_console_id");

**Comment by rdhandapani88** [comment]
Changed the console id, and tested again, getting the same error 

FAILED: installFromUrlTest
com.rokuality.core.exceptions.SessionNotStartedException: Failed to connect device c1acd34c.c95c2cef.470c6e59.1cbaf207.01 with the XBox Smartglass api server with result code 403.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.rokuality.core.driver.ServerPostHandler.postToServerWithHandling(ServerPostHandler.java:25)
	at com.rokuality.core.driver.xbox.XBoxDriver.<init>(XBoxDriver.java:37)
	at com.rokuality.test.tests.XBoxTests.installFromUrlTest(XBoxTests.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

**Comment by baclark774** [comment]
That id still looks off. Sure that's not the console id? You want the **xbox live id** of the device. You can find it from your dev console at:

https://your_xbox_device_ip:11443/#Settings

**Comment by rdhandapani88** [comment]
FAILED: launchAlreadyInstalledApp
com.rokuality.core.exceptions.SessionNotStartedException: Failed to connect device FD000EF570C0476B with the XBox Smartglass api server with result code 403.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.rokuality.core.driver.ServerPostHandler.postToServerWithHandling(ServerPostHandler.java:25)
	at com.rokuality.core.driver.xbox.XBoxDriver.<init>(XBoxDriver.java:37)
	at com.rokuality.test.tests.XBoxTests.launchAlreadyInstalledApp(XBoxTests.java:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

**Comment by rdhandapani88** [comment]
Attaching the Rest server logs,

xbox-rest-server
[2020-02-07 12:36:34,650] INFO in rest_server: Starting Xbox Smartglass REST server started on 0.0.0.0:5557
[2020-02-07 12:36:34,650] DEBUG in rest_server: Setting tokenfile path to /Users/a206639227/Library/Application Support/xbox/tokens.json
[2020-02-07 12:36:34,650] INFO in rest_server: Trying to load & refresh tokens
[2020-02-07 12:36:34,653] INFO in manager: Loaded token <class 'xbox.webapi.authentication.token.AccessToken'> from file
[2020-02-07 12:36:34,653] INFO in manager: Loaded token <class 'xbox.webapi.authentication.token.RefreshToken'> from file
[2020-02-07 12:36:34,653] INFO in manager: Loaded token <class 'xbox.webapi.authentication.token.UserToken'> from file
[2020-02-07 12:36:34,654] INFO in manager: Loaded token <class 'xbox.webapi.authentication.token.XSTSToken'> from file
[2020-02-07 12:36:34,661] DEBUG in connectionpool: Starting new HTTPS connection (1): login.live.com:443
[2020-02-07 12:36:34,829] DEBUG in connectionpool: https://login.live.com:443 "GET /oauth20_token.srf?grant_type=refresh_token&client_id=0000000048093EE3&scope=service%3A%3Auser.auth.xboxlive.com%3A%3AMBI_SSL&refresh_token=MCVZFlRtubPYbgODrooFYNxmobQIYD%21X3mTvrY4JSR1LyMYd4K3LUYKNJAveZyWQSHcOm5LUEPLDHCmMJ0xqf%2AEXwV5gYqw0Hz9CVQP7GmFnN5%2AWTjDM8%2AGgGDAEdNAs2qURsXlAGBYpM3rZ5FoKhK8bWg9tIbLpQ0%21Avz2p%21IsMdSuDWSrtEG0XVfce3xzsCgseAb%2A9IN%2A1pWLQe%21%2AriDBsOuDG3IcJinsPJChnmr5dQyjmyNSo1qlH%21lTwpujvE2Cf8GMgqQEU2p%2AYnW%2117%21q61LaTuLY4Bnv5mF8RlZJLtaxzAaxAQxKAGsqwnNm6MwIY7b50b4ZeLaHs90BJ7WgCHn2RsctY4Wz31BZQyl1Sb HTTP/1.1" 200 1560
127.0.0.1 - - [2020-02-07 12:36:38] "GET / HTTP/1.1" 200 1129 0.000743
127.0.0.1 - - [2020-02-07 12:36:38] "GET /favicon.ico HTTP/1.1" 404 356 0.000670
[2020-02-07 12:37:06,083] ERROR in app: {'success': False, 'message': 'Console info for FD000EF570C0476B is not available'}
127.0.0.1 - - [2020-02-07 12:37:06] "GET /device/FD000EF570C0476B HTTP/1.1" 403 196 0.001300
127.0.0.1 - - [2020-02-07 12:37:06] "GET /auth/login HTTP/1.1" 200 595 0.005526
127.0.0.1 - - [2020-02-07 12:37:06] "GET /static/style.css HTTP/1.1" 200 1658 0.001088
127.0.0.1 - - [2020-02-07 12:37:09] "GET /device HTTP/1.1" 200 138 2.529630
[2020-02-07 12:37:09,214] ERROR in app: {'success': False, 'message': 'Console info for FD000EF570C0476B is not available'}
127.0.0.1 - - [2020-02-07 12:37:09] "GET /device/FD000EF570C0476B/connect HTTP/1.1" 403 196 0.001304
Killed: 9

**Comment by rdhandapani88** [comment]
Restarted the console, twice and it started working. Thanks for this, Will keep you posted about the progress.

**Comment by baclark774** [comment]
Awesome. Glad to hear it's working. Let us know if you encounter any issues. A brand new implementation so likely some bugs to be addressed.

**Comment by rdhandapani88** [comment]
Closing this, as the new driver is working fine with out Harmony hub. Will create a new issue for the HDMI devices connections
