### ISSUE TITLE
Tizen app is not getting installed 

### ISSUE THREAD

**Issue by Diptimayee1993** [rokuality/rokuality-java#52]
FAILED: basicFinderTest
com.rokuality.core.exceptions.SessionNotStartedException: Failed to install app! The app package must be a url or local path to a valid Tizen .wgt package!
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at com.rokuality.core.driver.ServerPostHandler.postToServerWithHandling(ServerPostHandler.java:24)
	at com.rokuality.core.driver.tizentv.TizenTVDriver.<init>(TizenTVDriver.java:37)
	at com.rokuality.test.tests.TizenTests.basicFinderTest(TizenTests.java:73)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

**Comment by rokualitysupport** [comment]
Can you share your server logs so we can diagnose? Also, you're updating the 'DeviceID' and 'DeviceIPAddress' capabilities to reflect your tizen tv? You should be able to see your device via 'sdb devices' from the terminal.

**Comment by Diptimayee1993** [comment]
Hi i have tizen studio 4.1 and able to get device id using sdb devices 

please find last few logs from rokuality server .


--------------------------------


'
2021-03-11 18:39:02.379  INFO log - Starting new session.
2021-03-11 18:39:02.386  INFO log - No ocr type provided.
2021-03-11 18:39:02.792  INFO log - Tizen device UA43TU8570UXXL connected result: List of devices attached 
192.168.1.113:26101 	device    	UA43TU8570UXXL

2021-03-11 18:39:02.793  INFO log - Using prepared server url http://192.168.1.112:7777 during Tizen app installation.
2021-03-11 18:39:02.799  INFO log - App is base64 string. Converting to a file.
2021-03-11 18:39:02.899  INFO log - Installing url/file app and launching.
2021-03-11 18:39:03.320  INFO log - Appending html capture javascript to tizen app file at: C:\Users\Lenovo\AppData\Local\Temp\Rokuality\b1f2204a-04f0-48e7-a8e3-737d14839508\index.html
2021-03-11 18:39:03.354  INFO log - Packaging Tizen web package from directory: C:\Users\Lenovo\AppData\Local\Temp\Rokuality\b1f2204a-04f0-48e7-a8e3-737d14839508
2021-03-11 18:39:08.979  INFO log - Prepared wgt C:\Users\Lenovo\AppData\Local\Temp\Rokuality\b1f2204a-04f0-48e7-a8e3-737d14839508\OfflineClockImage.wgt exists: true
2021-03-11 18:39:09.026  INFO log - File moved: true
2021-03-11 18:39:09.027  INFO log - Ready wgt C:\Users\Lenovo\AppData\Local\Temp\Rokuality\374abc97-b4e8-42af-baa9-0bb1cc51fb1d.wgt exists: true
2021-03-11 18:39:12.959  INFO log - Tizen app uninstall result: Package ID is not valid. Please check the package ID again.
Total time: 00:00:00.636

2021-03-11 18:39:12.959  INFO log - Installing tizen app package 'C:\Users\Lenovo\AppData\Local\Temp\Rokuality\374abc97-b4e8-42af-baa9-0bb1cc51fb1d.wgt' on device 'UA43TU8570UXXL'.
2021-03-11 18:39:18.262  WARN log - App package at C:\Users\Lenovo\AppData\Local\Temp\Rokuality\374abc97-b4e8-42af-baa9-0bb1cc51fb1d.wgt did not install on device UA43TU8570UXXL with command C:\tizen-studio\tools\ide\bin\tizen.bat install -n 374abc97-b4e8-42af-baa9-0bb1cc51fb1d.wgt -t UA43TU8570UXXL -- C:\Users\Lenovo\AppData\Local\Temp\Rokuality and output 'Transferring the package...
Transferred the package: C:\Users\Lenovo\AppData\Local\Temp\Rokuality\374abc97-b4e8-42af-baa9-0bb1cc51fb1d.wgt -> /home/owner/share/tmp/sdk_tools/tmp
Installing the package...
--------------------
Platform log view
--------------------
install 8fhECWaWg0.OfflineClockImage
package_path /home/owner/share/tmp/sdk_tools/tmp/374abc97-b4e8-42af-baa9-0bb1cc51fb1d.wgt
app_id[8fhECWaWg0.OfflineClockImage] install start
app_id[8fhECWaWg0.OfflineClockImage] installing[10]
app_id[8fhECWaWg0.OfflineClockImage] installing[13]
app_id[8fhECWaWg0.OfflineClockImage] installing[15]
app_id[8fhECWaWg0.OfflineClockImage] installing[18]
app_id[8fhECWaWg0.OfflineClockImage] installing[21]
app_id[8fhECWaWg0.OfflineClockImage] installing[23]
app_id[8fhECWaWg0.OfflineClockImage] installing[26]
app_id[8fhECWaWg0.OfflineClockImage] install failed[118, -12], reason: Check certificate error : :Invalid signature. Signed with wrong key, changed signature file or changed package file.:<-4>
spend time for wascmd is [636]ms
Failed to install Tizen application.
Total time: 00:00:02.079
'
2021-03-11 18:39:51.696  INFO log - Starting new session.
2021-03-11 18:39:51.696  INFO log - No ocr type provided.
2021-03-11 18:39:51.849  INFO log - Tizen device UA43TU8570UXXL connected result: List of devices attached 
192.168.1.113:26101 	device    	UA43TU8570UXXL

2021-03-11 18:39:51.849  INFO log - Using prepared server url http://192.168.1.112:7777 during Tizen app installation.
2021-03-11 18:39:51.851  INFO log - App is base64 string. Converting to a file.
2021-03-11 18:39:51.878  INFO log - Installing url/file app and launching.
2021-03-11 18:39:52.065  INFO log - Appending html capture javascript to tizen app file at: C:\Users\Lenovo\AppData\Local\Temp\Rokuality\4f728da9-f916-48e4-996d-63448d2cdc44\index.html
2021-03-11 18:39:52.074  INFO log - Packaging Tizen web package from directory: C:\Users\Lenovo\AppData\Local\Temp\Rokuality\4f728da9-f916-48e4-996d-63448d2cdc44
2021-03-11 18:39:55.448  INFO log - Prepared wgt C:\Users\Lenovo\AppData\Local\Temp\Rokuality\4f728da9-f916-48e4-996d-63448d2cdc44\OfflineClockImage.wgt exists: true
2021-03-11 18:39:55.560  INFO log - File moved: true
2021-03-11 18:39:55.560  INFO log - Ready wgt C:\Users\Lenovo\AppData\Local\Temp\Rokuality\66af1c62-cbdc-44bb-87b6-d84421a2b9a9.wgt exists: true
2021-03-11 18:39:59.415  INFO log - Tizen app uninstall result: Package ID is not valid. Please check the package ID again.
Total time: 00:00:00.620

2021-03-11 18:39:59.415  INFO log - Installing tizen app package 'C:\Users\Lenovo\AppData\Local\Temp\Rokuality\66af1c62-cbdc-44bb-87b6-d84421a2b9a9.wgt' on device 'UA43TU8570UXXL'.
2021-03-11 18:40:04.515  WARN log - App package at C:\Users\Lenovo\AppData\Local\Temp\Rokuality\66af1c62-cbdc-44bb-87b6-d84421a2b9a9.wgt did not install on device UA43TU8570UXXL with command C:\tizen-studio\tools\ide\bin\tizen.bat install -n 66af1c62-cbdc-44bb-87b6-d84421a2b9a9.wgt -t UA43TU8570UXXL -- C:\Users\Lenovo\AppData\Local\Temp\Rokuality and output 'Transferring the package...
Transferred the package: C:\Users\Lenovo\AppData\Local\Temp\Rokuality\66af1c62-cbdc-44bb-87b6-d84421a2b9a9.wgt -> /home/owner/share/tmp/sdk_tools/tmp
Installing the package...
--------------------
Platform log view
--------------------
install 8fhECWaWg0.OfflineClockImage
package_path /home/owner/share/tmp/sdk_tools/tmp/66af1c62-cbdc-44bb-87b6-d84421a2b9a9.wgt
app_id[8fhECWaWg0.OfflineClockImage] install start
app_id[8fhECWaWg0.OfflineClockImage] installing[10]
app_id[8fhECWaWg0.OfflineClockImage] installing[13]
app_id[8fhECWaWg0.OfflineClockImage] installing[15]
app_id[8fhECWaWg0.OfflineClockImage] installing[18]
app_id[8fhECWaWg0.OfflineClockImage] installing[21]
app_id[8fhECWaWg0.OfflineClockImage] installing[23]
app_id[8fhECWaWg0.OfflineClockImage] installing[26]
app_id[8fhECWaWg0.OfflineClockImage] install failed[118, -12], reason: Check certificate error : :Invalid signature. Signed with wrong key, changed signature file or changed package file.:<-4>
spend time for wascmd is [650]ms
Failed to install Tizen application.
Total time: 00:00:02.058
'
2021-03-11 18:43:31.444  INFO log - Starting new session.
2021-03-11 18:43:31.444  INFO log - No ocr type provided.
2021-03-11 18:43:31.547  INFO log - Tizen device UA43TU8570UXXL connected result: List of devices attached 
192.168.1.113:26101 	device    	UA43TU8570UXXL

2021-03-11 18:43:31.547  INFO log - Using prepared server url http://192.168.1.112:7777 during Tizen app installation.
2021-03-11 18:43:31.548  INFO log - App is base64 string. Converting to a file.
2021-03-11 18:43:31.635  INFO log - Installing url/file app and launching.
2021-03-11 18:43:32.101  INFO log - Appending html capture javascript to tizen app file at: C:\Users\Lenovo\AppData\Local\Temp\Rokuality\a694a291-96be-4ca8-8392-9823bbd1fb92\index.html
2021-03-11 18:43:32.111  INFO log - Packaging Tizen web package from directory: C:\Users\Lenovo\AppData\Local\Temp\Rokuality\a694a291-96be-4ca8-8392-9823bbd1fb92
2021-03-11 18:43:35.978  INFO log - Prepared wgt C:\Users\Lenovo\AppData\Local\Temp\Rokuality\a694a291-96be-4ca8-8392-9823bbd1fb92\OfflineClockImage.wgt exists: true
2021-03-11 18:43:36.025  INFO log - File moved: true
2021-03-11 18:43:36.026  INFO log - Ready wgt C:\Users\Lenovo\AppData\Local\Temp\Rokuality\4c918cf2-c930-4f36-83a6-c47127fa0110.wgt exists: true
2021-03-11 18:43:39.719  INFO log - Tizen app uninstall result: Package ID is not valid. Please check the package ID again.
Total time: 00:00:00.573

2021-03-11 18:43:39.719  INFO log - Installing tizen app package 'C:\Users\Lenovo\AppData\Local\Temp\Rokuality\4c918cf2-c930-4f36-83a6-c47127fa0110.wgt' on device 'UA43TU8570UXXL'.
2021-03-11 18:43:44.655  WARN log - App package at C:\Users\Lenovo\AppData\Local\Temp\Rokuality\4c918cf2-c930-4f36-83a6-c47127fa0110.wgt did not install on device UA43TU8570UXXL with command C:\tizen-studio\tools\ide\bin\tizen.bat install -n 4c918cf2-c930-4f36-83a6-c47127fa0110.wgt -t UA43TU8570UXXL -- C:\Users\Lenovo\AppData\Local\Temp\Rokuality and output 'Transferring the package...
Transferred the package: C:\Users\Lenovo\AppData\Local\Temp\Rokuality\4c918cf2-c930-4f36-83a6-c47127fa0110.wgt -> /home/owner/share/tmp/sdk_tools/tmp
Installing the package...
--------------------
Platform log view
--------------------
install 8fhECWaWg0.OfflineClockImage
package_path /home/owner/share/tmp/sdk_tools/tmp/4c918cf2-c930-4f36-83a6-c47127fa0110.wgt
app_id[8fhECWaWg0.OfflineClockImage] install start
app_id[8fhECWaWg0.OfflineClockImage] installing[10]
app_id[8fhECWaWg0.OfflineClockImage] installing[13]
app_id[8fhECWaWg0.OfflineClockImage] installing[15]
app_id[8fhECWaWg0.OfflineClockImage] installing[18]
app_id[8fhECWaWg0.OfflineClockImage] installing[21]
app_id[8fhECWaWg0.OfflineClockImage] installing[23]
app_id[8fhECWaWg0.OfflineClockImage] installing[26]
app_id[8fhECWaWg0.OfflineClockImage] install failed[118, -12], reason: Check certificate error : :Invalid signature. Signed with wrong key, changed signature file or changed package file.:<-4>
spend time for wascmd is [638]ms
Failed to install Tizen application.
Total time: 00:00:02.062
'
2021-03-11 23:01:12.450  INFO log - Starting new session.
2021-03-11 23:01:12.735  INFO log - No ocr type provided.
2021-03-11 23:01:13.903  INFO log - Tizen device UA43TU8570UXXL connected result: List of devices attached 
192.168.1.113:26101 	device    	UA43TU8570UXXL

2021-03-11 23:01:13.926  INFO log - Using prepared server url http://192.168.1.112:7777 during Tizen app installation.
2021-03-11 23:01:13.945  INFO log - App is base64 string. Converting to a file.
2021-03-11 23:01:14.257  INFO log - Installing url/file app and launching.
2021-03-11 23:01:17.635  INFO log - Appending html capture javascript to tizen app file at: C:\Users\Lenovo\AppData\Local\Temp\Rokuality\a2d2705a-744a-4dd1-934a-de287221b636\index.html
2021-03-11 23:01:17.804  INFO log - Packaging Tizen web package from directory: C:\Users\Lenovo\AppData\Local\Temp\Rokuality\a2d2705a-744a-4dd1-934a-de287221b636
2021-03-11 23:01:25.047  INFO log - Prepared wgt C:\Users\Lenovo\AppData\Local\Temp\Rokuality\a2d2705a-744a-4dd1-934a-de287221b636\OfflineClockImage.wgt exists: true
2021-03-11 23:01:25.168  INFO log - File moved: true
2021-03-11 23:01:25.168  INFO log - Ready wgt C:\Users\Lenovo\AppData\Local\Temp\Rokuality\9524de56-1de0-45b8-bfab-9813ddd3d00a.wgt exists: true
2021-03-11 23:01:28.483  INFO log - Tizen app uninstall result: Package ID is not valid. Please check the package ID again.
Total time: 00:00:00.631

2021-03-11 23:01:28.483  INFO log - Installing tizen app package 'C:\Users\Lenovo\AppData\Local\Temp\Rokuality\9524de56-1de0-45b8-bfab-9813ddd3d00a.wgt' on device 'UA43TU8570UXXL'.
2021-03-11 23:01:32.905  WARN log - App package at C:\Users\Lenovo\AppData\Local\Temp\Rokuality\9524de56-1de0-45b8-bfab-9813ddd3d00a.wgt did not install on device UA43TU8570UXXL with command C:\tizen-studio\tools\ide\bin\tizen.bat install -n 9524de56-1de0-45b8-bfab-9813ddd3d00a.wgt -t UA43TU8570UXXL -- C:\Users\Lenovo\AppData\Local\Temp\Rokuality and output 'Transferring the package...
Transferred the package: C:\Users\Lenovo\AppData\Local\Temp\Rokuality\9524de56-1de0-45b8-bfab-9813ddd3d00a.wgt -> /home/owner/share/tmp/sdk_tools/tmp
Installing the package...
--------------------
Platform log view
--------------------
install 8fhECWaWg0.OfflineClockImage
package_path /home/owner/share/tmp/sdk_tools/tmp/9524de56-1de0-45b8-bfab-9813ddd3d00a.wgt
app_id[8fhECWaWg0.OfflineClockImage] install start
app_id[8fhECWaWg0.OfflineClockImage] installing[10]
app_id[8fhECWaWg0.OfflineClockImage] installing[13]
app_id[8fhECWaWg0.OfflineClockImage] installing[15]
app_id[8fhECWaWg0.OfflineClockImage] installing[18]
app_id[8fhECWaWg0.OfflineClockImage] installing[21]
app_id[8fhECWaWg0.OfflineClockImage] installing[23]
app_id[8fhECWaWg0.OfflineClockImage] installing[26]
app_id[8fhECWaWg0.OfflineClockImage] install failed[118, -12], reason: Check certificate error : :Invalid signature. Signed with wrong key, changed signature file or changed package file.:<-4>
spend time for wascmd is [749]ms
Failed to install Tizen application.
Total time: 00:00:02.080
'
2021-03-11 23:02:14.025  INFO log - Starting new session.
2021-03-11 23:02:14.025  INFO log - No ocr type provided.
2021-03-11 23:02:21.571  INFO log - Tizen device UA43TU8570UXXL connected result: List of devices attached 
192.168.1.113:26101 	device    	UA43TU8570UXXL

2021-03-11 23:02:21.571  INFO log - Using prepared server url http://192.168.1.112:7777 during Tizen app installation.
2021-03-11 23:02:21.572  INFO log - App is base64 string. Converting to a file.
2021-03-11 23:02:21.633  INFO log - Installing url/file app and launching.
2021-03-11 23:02:22.020  INFO log - Appending html capture javascript to tizen app file at: C:\Users\Lenovo\AppData\Local\Temp\Rokuality\e04db5eb-bd88-494d-8f3b-73e5ab5f326f\index.html
2021-03-11 23:02:22.038  INFO log - Packaging Tizen web package from directory: C:\Users\Lenovo\AppData\Local\Temp\Rokuality\e04db5eb-bd88-494d-8f3b-73e5ab5f326f
2021-03-11 23:02:27.817  INFO log - Prepared wgt C:\Users\Lenovo\AppData\Local\Temp\Rokuality\e04db5eb-bd88-494d-8f3b-73e5ab5f326f\OfflineClockImage.wgt exists: true
2021-03-11 23:02:27.930  INFO log - File moved: true
2021-03-11 23:02:27.931  INFO log - Ready wgt C:\Users\Lenovo\AppData\Local\Temp\Rokuality\0f2bf228-689b-4c08-b2ba-5a47bd41036b.wgt exists: true
2021-03-11 23:02:31.459  INFO log - Tizen app uninstall result: Package ID is not valid. Please check the package ID again.
Total time: 00:00:00.819

2021-03-11 23:02:31.459  INFO log - Installing tizen app package 'C:\Users\Lenovo\AppData\Local\Temp\Rokuality\0f2bf228-689b-4c08-b2ba-5a47bd41036b.wgt' on device 'UA43TU8570UXXL'.
2021-03-11 23:02:36.001  WARN log - App package at C:\Users\Lenovo\AppData\Local\Temp\Rokuality\0f2bf228-689b-4c08-b2ba-5a47bd41036b.wgt did not install on device UA43TU8570UXXL with command C:\tizen-studio\tools\ide\bin\tizen.bat install -n 0f2bf228-689b-4c08-b2ba-5a47bd41036b.wgt -t UA43TU8570UXXL -- C:\Users\Lenovo\AppData\Local\Temp\Rokuality and output 'Transferring the package...
Transferred the package: C:\Users\Lenovo\AppData\Local\Temp\Rokuality\0f2bf228-689b-4c08-b2ba-5a47bd41036b.wgt -> /home/owner/share/tmp/sdk_tools/tmp
Installing the package...
--------------------
Platform log view
--------------------
install 8fhECWaWg0.OfflineClockImage
package_path /home/owner/share/tmp/sdk_tools/tmp/0f2bf228-689b-4c08-b2ba-5a47bd41036b.wgt
app_id[8fhECWaWg0.OfflineClockImage] install start
app_id[8fhECWaWg0.OfflineClockImage] installing[10]
app_id[8fhECWaWg0.OfflineClockImage] installing[13]
app_id[8fhECWaWg0.OfflineClockImage] installing[15]
app_id[8fhECWaWg0.OfflineClockImage] installing[18]
app_id[8fhECWaWg0.OfflineClockImage] installing[21]
app_id[8fhECWaWg0.OfflineClockImage] installing[23]
app_id[8fhECWaWg0.OfflineClockImage] installing[26]
app_id[8fhECWaWg0.OfflineClockImage] install failed[118, -12], reason: Check certificate error : :Invalid signature. Signed with wrong key, changed signature file or changed package file.:<-4>
spend time for wascmd is [677]ms
Failed to install Tizen application.
Total time: 00:00:02.144
'
2021-03-11 23:07:20.432  INFO log - Starting new session.
2021-03-11 23:07:20.480  INFO log - No ocr type provided.
2021-03-11 23:07:21.038  INFO log - Tizen device UA43TU8570UXXL connected result: List of devices attached 

2021-03-11 23:07:23.175  INFO log - Tizen device 192.168.1.113 connect result: connecting to 192.168.1.113:26101 ...
connected to 192.168.1.113:26101

2021-03-11 23:07:23.580  INFO log - Tizen device UA43TU8570UXXL connected result: List of devices attached 
192.168.1.113:26101 	device    	UA43TU8570UXXL

2021-03-11 23:07:23.580  INFO log - Using prepared server url http://192.168.1.112:7777 during Tizen app installation.
2021-03-11 23:07:23.580  INFO log - App is base64 string. Converting to a file.
2021-03-11 23:07:23.593  INFO log - Installing url/file app and launching.
2021-03-11 23:07:23.828  INFO log - Appending html capture javascript to tizen app file at: C:\Users\Lenovo\AppData\Local\Temp\Rokuality\619a03e4-24b3-4b15-90fe-5cc25885ad83\index.html
2021-03-11 23:07:23.837  INFO log - Packaging Tizen web package from directory: C:\Users\Lenovo\AppData\Local\Temp\Rokuality\619a03e4-24b3-4b15-90fe-5cc25885ad83
2021-03-11 23:07:29.779  INFO log - Prepared wgt C:\Users\Lenovo\AppData\Local\Temp\Rokuality\619a03e4-24b3-4b15-90fe-5cc25885ad83\OfflineClockImage.wgt exists: true
2021-03-11 23:07:32.410  INFO log - File moved: true
2021-03-11 23:07:32.411  INFO log - Ready wgt C:\Users\Lenovo\AppData\Local\Temp\Rokuality\c063eeda-1c7c-4659-a4b2-66538fcd6a6d.wgt exists: true
2021-03-11 23:07:36.828  INFO log - Tizen app uninstall result: Package ID is not valid. Please check the package ID again.
Total time: 00:00:00.664

2021-03-11 23:07:36.995  INFO log - Installing tizen app package 'C:\Users\Lenovo\AppData\Local\Temp\Rokuality\c063eeda-1c7c-4659-a4b2-66538fcd6a6d.wgt' on device 'UA43TU8570UXXL'.
2021-03-11 23:07:42.227  WARN log - App package at C:\Users\Lenovo\AppData\Local\Temp\Rokuality\c063eeda-1c7c-4659-a4b2-66538fcd6a6d.wgt did not install on device UA43TU8570UXXL with command C:\tizen-studio\tools\ide\bin\tizen.bat install -n c063eeda-1c7c-4659-a4b2-66538fcd6a6d.wgt -t UA43TU8570UXXL -- C:\Users\Lenovo\AppData\Local\Temp\Rokuality and output 'Transferring the package...
Transferred the package: C:\Users\Lenovo\AppData\Local\Temp\Rokuality\c063eeda-1c7c-4659-a4b2-66538fcd6a6d.wgt -> /home/owner/share/tmp/sdk_tools/tmp
Installing the package...
--------------------
Platform log view
--------------------
install 8fhECWaWg0.OfflineClockImage
package_path /home/owner/share/tmp/sdk_tools/tmp/c063eeda-1c7c-4659-a4b2-66538fcd6a6d.wgt
app_id[8fhECWaWg0.OfflineClockImage] install start
app_id[8fhECWaWg0.OfflineClockImage] installing[10]
app_id[8fhECWaWg0.OfflineClockImage] installing[13]
app_id[8fhECWaWg0.OfflineClockImage] installing[15]
app_id[8fhECWaWg0.OfflineClockImage] installing[18]
app_id[8fhECWaWg0.OfflineClockImage] installing[21]
app_id[8fhECWaWg0.OfflineClockImage] installing[23]
app_id[8fhECWaWg0.OfflineClockImage] installing[26]
app_id[8fhECWaWg0.OfflineClockImage] install failed[118, -12], reason: Check certificate error : :Invalid signature. Signed with wrong key, changed signature file or changed package file.:<-4>
spend time for wascmd is [660]ms
Failed to install Tizen application.
Total time: 00:00:02.085

**Comment by swadhinacharya-gl** [comment]
is this issue resolved ? i am  also facing the same issue

**Comment by rokualitysupport** [comment]
Looks like the wgt install is failing because the certificate signing is invalid. wgt packages have to be signed for the device they are being installed on. Most likely you don't have a profiles.xml configuration setup. I would start by trying the newly releases rokuality 1.2.0 app from https://www.rokuality.com/download and see if this resolves. This latest release will automatically generate a tizen automation signing profile during the tizen app installation. Let me know if this resolves your issue.
